In [2]:
import torch
import torch.nn.functional as F
import torch.nn as nn
# import torch.optim as optim
# import torch_optimizer as optim
import torch.nn.init as init

import matplotlib.pyplot as plt
from torch.utils.data import Dataset
from torch.utils.data import DataLoader
import pandas as pd
import numpy as np
import math
from sklearn.model_selection import train_test_split
import adabound
from sys import stdout
from tqdm import tqdm
from tqdm import trange
import seaborn as sns

import time
from datetime import datetime as dt

from tensorflow.keras.models import load_model

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/zorocrit/Control_Nuclear_Spins/master/C13spin/testdata.csv?token=GHSAT0AAAAAAB5HMDTB2GTBZHJM4PEGNKE2ZCHHGNA')
# df

In [4]:
# y = df[['x', 'N', 'z']]
# # y

y = df[['Xtau', 'XN']]
y

           Xtau    XN
0      2.959641  10.0
1      4.245750   7.0
2      3.594517  10.0
3      0.479873  16.0
4      2.861716  13.0
...         ...   ...
36744  2.910000  13.0
36745  4.258442   9.0
36746  1.675000  13.0
36747  2.935000  22.0
36748  3.095000   7.0

[36749 rows x 2 columns]

In [5]:
X = df[['Al', 'Ap']]
# X

In [6]:
X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.10, random_state=100)

In [7]:
Xdata = list(np.array(X_train.values.tolist()))
print(Xdata.__len__())

33074

In [8]:
ydata = list(np.array(y_train.values.tolist()))
# print(ydata)

In [9]:
torch.manual_seed(1)

In [10]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

# for reproducibility
torch.manual_seed(777)
if device == 'cuda':
    torch.cuda.manual_seed_all(777)
print(device)

cpu

In [11]:
x = torch.FloatTensor(Xdata).to(device)
y = torch.FloatTensor(ydata).to(device)

C:\Users\KIST3\AppData\Local\Temp\ipykernel_10856\2245922195.py:1: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at ..\torch\csrc\utils\tensor_new.cpp:248.)
  x = torch.FloatTensor(Xdata).to(device)

In [12]:
num_data = Xdata.__len__()

num_epoch = 2000000

In [13]:
from sys import stdout


model = nn.Sequential(

    nn.Linear(2,300),

    nn.ReLU(),

    nn.Linear(300,300),

    nn.ReLU(),

    nn.Linear(300,300),

    nn.ReLU(),
    
    nn.Linear(300,300),

    nn.ReLU(),
    
    nn.Linear(300,300),

    nn.ReLU(),
    
    nn.Linear(300,300),

    nn.ReLU(),
    
    nn.Linear(300,300),

    nn.ReLU(),
    
    nn.Linear(300,300),

    nn.ReLU(),

    nn.Linear(300,2)

).to(device)

#ReLU라는 Activation Function을 사용하여, 4개의 Linear Layer로 모델 구현

# Input layer에 1개씩 데이터가 들어가므로 nn.Linear(1,2)이며, 최종적으로 1개의 값이 나와야하기에 Output Layer는 nn.Linear(4,1)

In [ ]:
 

loss_func = nn.L1Loss().to(device)

# optimizer = optim.SGD(model.parameters(),lr = 0.0002)

# optimizer = adabound.AdaBound(model.parameters(), lr=0.935 * 1e-4, final_lr=0.05758)  #Loss: 0.0537

# optimizer = adabound.AdaBound(model.parameters(), lr=0.435 * 1e-3, final_lr=0.05558)

optimizer = adabound.AdaBound(model.parameters(), lr=0.935 * 1e-3, final_lr=0.04978)  #Loss: 0.0537

loss_array = []

minloss = 10

for i in tqdm(range(num_epoch)) : 

    optimizer.zero_grad()

    output = model(x)

    loss = loss_func(output,y)

    loss.backward()

    optimizer.step()

    if(loss < minloss):
       minloss = loss

    loss_array.append(loss)
    if(i == 1):
      stdout.write("Minimum loss: " + str(minloss))
    if(i%100000 == 0 and i != 0):
      # print("Case "+ str(i) + ", Loss: " + str(loss.data))
      stdout.write("Minimum loss: " + str(minloss))

    if i == num_epoch - 1:

        print(loss.data)

        param_list = list(model.parameters())

        #최종 학습된 마지막 결과물의 Parameter 저장

        print(param_list)

loss_array = torch.tensor(loss_array)

loss_array.detach().numpy()

plt.plot(loss_array)

plt.show()

#Loss(y_predicted - y_real)값이 어떻게 변하는지 그래프로 도식화

In [13]:
from datetime import datetime as dt
date = dt.now()

printdate = date.strftime('%Y%m%d_%H%M%S')
print(date)

torch.save(model.state_dict(), "Xmodel_" + printdate + ".h5")

2023-04-19 17:35:55.364353

In [16]:
# model = load_model("C:/Users/KIST3/Desktop/13C/ml_04.11/Xmodel_20230419_173555.h5")
model.load_state_dict(torch.load("Xmodel_20230419_173555.h5", map_location=device))
model.eval()

Sequential(
  (0): Linear(in_features=2, out_features=300, bias=True)
  (1): ReLU()
  (2): Linear(in_features=300, out_features=300, bias=True)
  (3): ReLU()
  (4): Linear(in_features=300, out_features=300, bias=True)
  (5): ReLU()
  (6): Linear(in_features=300, out_features=300, bias=True)
  (7): ReLU()
  (8): Linear(in_features=300, out_features=300, bias=True)
  (9): ReLU()
  (10): Linear(in_features=300, out_features=300, bias=True)
  (11): ReLU()
  (12): Linear(in_features=300, out_features=300, bias=True)
  (13): ReLU()
  (14): Linear(in_features=300, out_features=300, bias=True)
  (15): ReLU()
  (16): Linear(in_features=300, out_features=2, bias=True)
)

In [17]:
X_2 = list(np.array(X.values.tolist()))
X_2_tensor = torch.FloatTensor(X_2).to(device)
y_2_input = model(X_2_tensor)
y_2_input = np.array(y_2_input.tolist())
y_2_input

array([[ 2.96878338,  9.99699306],
       [ 4.43640709,  6.98709679],
       [ 3.61910868, 10.01675129],
       ...,
       [ 1.68283594, 13.00479031],
       [ 2.9416244 , 21.95355415],
       [ 3.10761285,  6.99611664]])

In [18]:
X_input = list(np.array(X_valid.values.tolist()))
new_var =  torch.FloatTensor(X_input).to(device)
y_input = model(new_var)
y_input = np.array(y_input.tolist())
y_input

array([[ 1.4715445 ,  9.91405964],
       [ 4.16308737, 10.01140594],
       [ 1.37726974,  6.99695826],
       ...,
       [ 1.47109985,  6.47761583],
       [ 4.35567141, 22.13625145],
       [ 4.01698875,  7.42737913]])

In [19]:
y_output = np.array(y_valid.values.tolist())
y_output

array([[ 4.35176188, 10.        ],
       [ 1.91      , 10.        ],
       [ 1.36831193,  7.        ],
       ...,
       [ 1.44176854,  7.        ],
       [ 4.37756871, 22.        ],
       [ 1.57982355, 10.        ]])

In [20]:
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

# MAE
print("X tau MAE: " + str(mean_absolute_error(y_input[:, 0], y_output[:, 0])))
print("X N MAE: " + str(mean_absolute_error(y_input[:, 1], y_output[:, 1])))
# print("Z tau MAE: " + str(mean_absolute_error(y_input[:, 2], y_output[:, 2])))
# print("Z N MAE: " + str(mean_absolute_error(y_input[:, 3], y_output[:, 3])))

print(' ')
#MSE
print("X tau MSE: " + str(mean_squared_error(y_input[:, 0], y_output[:, 0])))
print("X N MSE: " + str(mean_squared_error(y_input[:, 1], y_output[:, 1])))
# print("Z tau MSE: " + str(mean_squared_error(y_input[:, 2], y_output[:, 2])))
# print("Z N MSE: " + str(mean_squared_error(y_input[:, 3], y_output[:, 3])))

print(' ')
#r2
print("X tau r2: " + str(r2_score(y_input[:, 0], y_output[:, 0])))
print("X N r2: " + str(r2_score(y_input[:, 1], y_output[:, 1])))
# print("Z tau r2: " + str(r2_score(y_input[:, 2], y_output[:, 2])))
# print("Z N r2: " + str(r2_score(y_input[:, 3], y_output[:, 3])))

X tau MAE: 0.27118998947497486
X N MAE: 1.5229432882581437

X tau MSE: 0.5187856536903979
X N MSE: 16.648141847310296

X tau r2: 0.7098480771867661
X N r2: 0.3147041466231151

In [21]:
y2 = df[['Ztau', 'ZN']]
y2

           Ztau    ZN
0      0.176380   1.0
1      0.625249  22.0
2      1.129403   1.0
3      0.059788   1.0
4      0.197018   4.0
...         ...   ...
36744  1.273125  10.0
36745  2.132500   1.0
36746  0.209375   7.0
36747  0.917188   1.0
36748  0.580313   7.0

[36749 rows x 2 columns]

In [22]:
x2 = df[['Al', 'Ap']]
x2

             Al        Ap
0      1.977370  0.765909
1      2.673387  1.847034
2      0.572199  1.815541
3      1.159075  0.425780
4      4.427746  0.920076
...         ...       ...
36744  4.275027  0.802606
36745  4.104650  1.576277
36746  3.926686  0.789887
36747  2.068772  0.314327
36748  1.657911  1.027535

[36749 rows x 2 columns]

In [23]:
x2_2 = y_2_input
x2_2 = pd.DataFrame(x2_2)
x2_2.rename(columns={0: "Xtau_pre", 1: "XN_pre"}, inplace=True)
x2_2

       Xtau_pre     XN_pre
0      2.968783   9.996993
1      4.436407   6.987097
2      3.619109  10.016751
3      0.487028  15.999538
4      2.876117  13.003598
...         ...        ...
36744  2.922971  13.003339
36745  4.259301   9.045465
36746  1.682836  13.004790
36747  2.941624  21.953554
36748  3.107613   6.996117

[36749 rows x 2 columns]

In [24]:
x2_fin = pd.concat([x2, x2_2], axis = 1)
x2_fin

             Al        Ap  Xtau_pre     XN_pre
0      1.977370  0.765909  2.968783   9.996993
1      2.673387  1.847034  4.436407   6.987097
2      0.572199  1.815541  3.619109  10.016751
3      1.159075  0.425780  0.487028  15.999538
4      4.427746  0.920076  2.876117  13.003598
...         ...       ...       ...        ...
36744  4.275027  0.802606  2.922971  13.003339
36745  4.104650  1.576277  4.259301   9.045465
36746  3.926686  0.789887  1.682836  13.004790
36747  2.068772  0.314327  2.941624  21.953554
36748  1.657911  1.027535  3.107613   6.996117

[36749 rows x 4 columns]

In [25]:
X_train, X_valid, y_train, y_valid = train_test_split(x2_fin, y2, test_size=0.10, random_state=100)

In [26]:
Xdata = list(np.array(X_train.values.tolist()))
Ydata = list(np.array(y_train.values.tolist()))
print(Xdata.__len__())

33074

In [27]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

# for reproducibility
torch.manual_seed(777)
if device == 'cuda':
    torch.cuda.manual_seed_all(777)
print(device)

cpu

In [28]:
x22 = torch.FloatTensor(Xdata).to(device)
y22 = torch.FloatTensor(Ydata).to(device)

In [31]:
num_data = Xdata.__len__()

num_epoch = 2250000

In [33]:
model2 = nn.Sequential(

    nn.Linear(4,400),

    nn.ReLU(),

    nn.Linear(400,400),

    nn.ReLU(),

    nn.Linear(400,400),
    
    nn.ReLU(),

    nn.Linear(400,400),
    
    nn.ReLU(),

    nn.Linear(400,400),
    
    nn.ReLU(),

    nn.Linear(400,400),
    
    nn.ReLU(),

    nn.Linear(400,400),
    
    nn.ReLU(),

    nn.Linear(400,400),
    
    nn.ReLU(),

    nn.Linear(400,2)

).to(device)

In [ ]:


#ReLU라는 Activation Function을 사용하여, 4개의 Linear Layer로 모델 구현

# Input layer에 1개씩 데이터가 들어가므로 nn.Linear(1,2)이며, 최종적으로 1개의 값이 나와야하기에 Output Layer는 nn.Linear(4,1)

 

loss_func = nn.L1Loss().to(device)

# optimizer = optim.SGD(model.parameters(),lr = 0.0002)

# optimizer = adabound.AdaBound(model.parameters(), lr=0.935 * 1e-4, final_lr=0.05758)  #Loss: 0.0537

# optimizer = adabound.AdaBound(model.parameters(), lr=0.435 * 1e-3, final_lr=0.05558)

optimizer = adabound.AdaBound(model2.parameters(), lr=0.935 * 1e-3, final_lr=0.05958)  #Loss: 0.0537

loss_array = []

minloss = 10

for i in tqdm(range(num_epoch)) : 

    optimizer.zero_grad()

    output = model2(x22)

    loss = loss_func(output,y22)

    loss.backward()

    optimizer.step()

    if(loss < minloss):
       minloss = loss

    loss_array.append(loss)
    if(i == 1):
      stdout.write("Minimum loss: " + str(minloss))
    if(i%100000 == 0 and i != 0):
      # print("Case "+ str(i) + ", Loss: " + str(loss.data))
      stdout.write("Minimum loss: " + str(minloss))

    if i == num_epoch - 1:

        print(loss.data)

        param_list = list(model.parameters())

        #최종 학습된 마지막 결과물의 Parameter 저장

        print(param_list)

loss_array = torch.tensor(loss_array)

loss_array.detach().numpy()

plt.plot(loss_array)

plt.show()

#Loss(y_predicted - y_real)값이 어떻게 변하는지 그래프로 도식화

In [30]:
from datetime import datetime as dt 
date = dt.now()

printdate = date.strftime('%Y%m%d_%H%M%S')
print(date)

torch.save(model2.state_dict(), "Zmodel2_" + printdate + ".h5")

2023-04-20 09:21:57.084097

In [35]:
# model = load_model("C:/Users/KIST3/Desktop/13C/ml_04.11/Xmodel_20230419_173555.h5")
model2.load_state_dict(torch.load("Zmodel2_20230420_092157.h5", map_location=device))
model2.eval()

Sequential(
  (0): Linear(in_features=4, out_features=400, bias=True)
  (1): ReLU()
  (2): Linear(in_features=400, out_features=400, bias=True)
  (3): ReLU()
  (4): Linear(in_features=400, out_features=400, bias=True)
  (5): ReLU()
  (6): Linear(in_features=400, out_features=400, bias=True)
  (7): ReLU()
  (8): Linear(in_features=400, out_features=400, bias=True)
  (9): ReLU()
  (10): Linear(in_features=400, out_features=400, bias=True)
  (11): ReLU()
  (12): Linear(in_features=400, out_features=400, bias=True)
  (13): ReLU()
  (14): Linear(in_features=400, out_features=400, bias=True)
  (15): ReLU()
  (16): Linear(in_features=400, out_features=2, bias=True)
)

In [36]:
X_input = list(np.array(X_valid.values.tolist()))
new_var =  torch.FloatTensor(X_input).to(device)
y_input2 = model2(new_var)
y_input2 = np.array(y_input2.tolist())
y_input2

y_output2 = np.array(y_valid.values.tolist())
y_output2

array([[0.949375  , 1.        ],
       [0.119375  , 4.        ],
       [0.12843749, 1.        ],
       ...,
       [0.09294756, 1.        ],
       [0.26633943, 4.        ],
       [0.34453125, 1.        ]])

In [37]:
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

# MAE
print("Z tau MAE: " + str(mean_absolute_error(y_input2[:, 0], y_output2[:, 0])))
print("Z N MAE: " + str(mean_absolute_error(y_input2[:, 1], y_output2[:, 1])))
# print("Z tau MAE: " + str(mean_absolute_error(y_input[:, 2], y_output[:, 2])))
# print("Z N MAE: " + str(mean_absolute_error(y_input[:, 3], y_output[:, 3])))

print(' ')
#MSE
print("Z tau MSE: " + str(mean_squared_error(y_input2[:, 0], y_output2[:, 0])))
print("Z N MSE: " + str(mean_squared_error(y_input2[:, 1], y_output2[:, 1])))
# print("Z tau MSE: " + str(mean_squared_error(y_input[:, 2], y_output[:, 2])))
# print("Z N MSE: " + str(mean_squared_error(y_input[:, 3], y_output[:, 3])))

print(' ')
#r2
print("Z tau r2: " + str(r2_score(y_input2[:, 0], y_output2[:, 0])))
print("Z N r2: " + str(r2_score(y_input2[:, 1], y_output2[:, 1])))
# print("Z tau r2: " + str(r2_score(y_input[:, 2], y_output[:, 2])))
# print("Z N r2: " + str(r2_score(y_input[:, 3], y_output[:, 3])))

Z tau MAE: 0.32171212721389103
Z N MAE: 4.340451100294282

Z tau MSE: 0.24844159316021952
Z N MSE: 50.75923129975894

Z tau r2: -0.2971611272304189
Z N r2: -0.9079950231980933

In [38]:
# Al = 2*math.pi*0.3
# Ap = 2*math.pi*0.3

number = 16

# Al    = 2*pi * random.uniform(0.05, 0.8) #[MHz] # A_|| hyperfine term
# Ap = 2*pi* random.uniform(0.05, 0.3) #[MHz] # A_per hyperfine term

Alarr = X_valid[['Al']]
Aparr = X_valid[['Ap']]
Alarr = list(np.array(Alarr))
Aparr = list(np.array(Aparr))



Al = Alarr[number]
Ap = Aparr[number]

Al = float(Al)
Ap = float(Ap)
AAin = torch.FloatTensor([[Al, Ap]]).to(device)

AA_predict = model(AAin)

AAA_predict = np.array(AA_predict.tolist())

In [39]:
AA_predict = AA_predict.tolist()
list(np.array(AA_predict))
AA_predict[0][1]

13.004240036010742

In [40]:
AAin2 = torch.FloatTensor([Al, Ap, AA_predict[0][0], AA_predict[0][1]]).to(device)
AAin2
# AAin2
# AAXtau = AA

tensor([ 4.3986,  0.9043,  2.8826, 13.0042])

In [41]:
AA2_predict = model2(AAin2)
AA2_predict = AA2_predict.cpu()
AA2_predict

tensor([0.6127, 1.0218], grad_fn=<AddBackward0>)

In [44]:
#3/20(월)
# initialization system
# 이 코드는 13C의 nuclear spin을 초기화 시키는 코드입니다.,·
# 각 gate의 파라미터를 찾아서 초기화 시킵니다.
# initial:mixed state, target : up state
from toqito.channels import partial_trace
from qutip import *
from PIL import Image
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from scipy import linalg
import math
import matplotlib.pyplot as plt
from scipy import optimize
import random
from math import *
import pandas as pd
import time
from datetime import datetime as dt                         # 시간을 출력하기 위한 라이브러리  
import random
from mpl_toolkits.mplot3d import Axes3D
from sys import stdout
from tqdm import tqdm
from tqdm import trange
from scipy.linalg import fractional_matrix_power

totalstart = time.time() #시작 시간 저장

#Generating gate function
def UO(B1,B2,a,D1,D2):
    i   = 1j
    gamma = 2*pi*2.8
    D     = 2870
    UA = [[(B2**2+B1**2*cos(a))/(B1**2+B2**2), -i*B1*(e**(-i*D1))*sin(a)/sqrt(B1**2+B2**2), ((-1+cos(a))*B1*B2*(e**(-i*(D1-D2))))/(B1**2+B2**2)],
            [-i*B1*(e**(i*D1))*sin(a)/sqrt(B1**2+B2**2), cos(a), -i*B2*(e**(i*D2))*sin(a)/sqrt(B1**2+B2**2)],
            [((-1+cos(a))*B1*B2*e**(i*(D1-D2)))/(B1**2+B2**2), -i*B2*(e**(-i*D2))*sin(a)/sqrt(B1**2+B2**2), (B1**2+B2**2*cos(a))/(B1**2+B2**2)]]
    return UA

## Define dimension, pauli matrices
i   = 1j #1j
sx  = 1/sqrt(2)*np.array([[0, 1, 0],[1, 0, 1], [0, 1, 0]])
sy  = 1/sqrt(2)/i*np.array([[0, 1, 0], [-1, 0, 1],[0, -1, 0]])
sz  = np.array([[1, 0, 0], [0, 0, 0], [0, 0, -1]])
#sz  = [1, 0, 0; 0, -1, 0; 0, 0, 0]
I   = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])

# Rotation matrix projected into 2 level system
Sxp  = np.array([[0, 1, 0], [1, 0, 0], [0, 0, 0]])
Sxm  = np.array([[0, 0, 0], [0, 0, 1], [0, 1, 0]])
Syp  = 1/i*np.array([[0, 1, 0], [-1, 0, 0], [0, 0, 0]])
Sym  = 1/i*np.array([[0, 0, 0], [0, 0, 1], [0, -1, 0]])
Szp  = np.array([[1, 0, 0], [0, -1, 0], [0, 0, 0]])

#Gellman matrix
Sx  = np.array([[0, 0, 1],[0, 0, 0], [1, 0, 0]])
Sy  = np.array([[0, 0, -i],[0, 0, 0], [i, 0, 0]])
Sz  = np.array([[1, 0, 0],[0, 0, 0], [0, 0, -1]])

# Pauli basis for 13C nuclear spin
Ix  = 1/2*np.array([[0, 0, 1], [0, 0, 0], [1, 0, 0]])   
Iy  = 1/2/i*np.array([[0, 0, 1], [0, 0, 0], [-1, 0, 0]])
Iz  = np.array([[1, 0, 0], [0, 0, 0], [0, 0, -1]])
 

## Define sweep parameters
Sweep = 1001
N = Sweep
B = 403 #[G] magnetic field

T = 5; # sweep tau [us]
t = np.linspace(0,T,N)
n = 32; # number of pi pulses

## Define gate operations
# Single Q ms=+1
U090xp = UO(1,0,pi/4,0,0)
U090xmp = UO(1,0,-pi/4,0,0)
U090yp = UO(1,0,pi/4,pi/2,0)
U090ymp = UO(1,0,-pi/4,pi/2,0)
U180xp = UO(1,0,pi/2,0,0)
U180xmp = UO(1,0,-pi/2,0,0)

#Single Q ms=-1
U090xm = UO(0,1,pi/4,0,0)
U090xmm = UO(0,1,-pi/4,0,0)
U180xm = UO(0,1,pi/2,0,0)
U180xmm = UO(0,1,pi/2,0,0)

# Define initial state of the system

irho_p = np.array([[1,0,0],[0,0,0],[0,0,0]]) #[0,0,0;0,0,0]

irho_m = np.array([[0,0,0],[0,0,0],[0,0,1]]) #[0,0,0;0,0,1]

irho_z = np.array([[0,0,0],[0,1,0],[0,0,0]]) #[0,1,0;0,0,0]

irho_mix = np.array([[1/2,0,0],[0,1/2,0],[0,0,0]]) #[1/2,0,0;0,1/2,0;0,0,0]

irho_Z = np.array([[0,0,0],[0,0,0],[0,0,1]]) #target state

irho_MIX = np.array([[1/2,0,0],[0,0,0],[0,0,1/2]])

irho = np.kron(irho_z,irho_MIX) #initial state
trace = [1, 1, 0, 100, 100, 1000, 100] # trace of the X, Y, Z, and total density matrices
vvv = [0, 0, 0, 0] 
bbb = [0, 0, 0, 0]
normalxyz = [0, 0, 0]
    
date = dt.now()
printdate = date.strftime('%Y%m%d_%H%M%S')
print(date)

def state_fidelity(rho_1, rho_2): #fidelity
        if np.shape(rho_1) != np.shape(rho_2):
            print("Dimensions of two states do not match.")
            return 0
        else:
            sqrt_rho_1 = fractional_matrix_power(rho_1, 1 / 2)
            fidelity = np.trace(fractional_matrix_power(sqrt_rho_1 @ rho_2 @ sqrt_rho_1, 1 / 2)) ** 2
            return np.real(fidelity)

def problem(vari): 
        #for e Ry(pi/2)
        rho1 = np.kron(U090yp,I)@irho@(np.kron(U090yp,I).conj().T)                              # Ry 90도

        #for N Rx(pi/2)
        U_e2=(U_H.conj().T)@(linalg.expm(-i*E* vari[0]/2)@U_H)                                  # for tau/2
        U_e=(U_H.conj().T)@(linalg.expm(-i*E* vari[0])@U_H)                                     # for tau
        rho2=U_e2@rho1@(U_e2.conj().T)                                                          # first tau/2
        for k in range(1,2*math.trunc(vari[1])):                                                # N과 tau를 N개 생성
            rho2 = U_e@np.kron(U180xp,I) @ rho2 @ (np.kron(U180xp,I).conj().T) @ (U_e.conj().T) # N & tau
        rho3 = U_e2 @ np.kron(U180xp,I) @ rho2 @ (np.kron(U180xp,I).conj().T) @ (U_e2.conj().T) # last N & tau/2

        #for e Rx(pi/2)
        rho4 = np.kron(U090xp,I)@rho3@(np.kron(U090xp,I).conj().T)                              # Rx 90도

        #for N Rz(pi/2) //이부분이 Z pulse를 다루고 있다면 N을 따로 분리해야하나?>
        U_e2=(U_H.conj().T)@(linalg.expm(-i*E*vari[2]/2)@U_H)                                   # for tau/2
        U_e=(U_H.conj().T)@(linalg.expm(-i*E*vari[2])@U_H)                                      # for tau/2
        rho5=U_e2@rho4@(U_e2.conj().T)                                                          # first tau/2
        for k in range(1,2*math.trunc(vari[3])):                                                # N과 tau를 N개 생성
            rho5 = U_e@np.kron(U180xp,I) @ rho5 @ (np.kron(U180xp,I).conj().T) @ (U_e.conj().T) # N & tau
        rho6 = U_e2 @ np.kron(U180xp,I) @ rho5 @ (np.kron(U180xp,I).conj().T) @ (U_e2.conj().T) # last N & tau/2

        #for N Rx(pi/2)
        U_e2=(U_H.conj().T)@(linalg.expm(-i*E* vari[0]/2)@U_H)                                  # for tau/2
        U_e=(U_H.conj().T)@(linalg.expm(-i*E* vari[0])@U_H)                                     # for tau
        rho7=U_e2@rho6@(U_e2.conj().T)                                                          # first tau/2
        for k in range(1,2*math.trunc(vari[1])):                                                # N과 tau를 N개 생성
            rho7 = U_e@np.kron(U180xp,I) @ rho7 @ (np.kron(U180xp,I).conj().T) @ (U_e.conj().T) # N & tau
        rho8 = U_e2 @ np.kron(U180xp,I) @ rho7 @ (np.kron(U180xp,I).conj().T) @ (U_e2.conj().T) # last N & tau/2

        # projection&trace
        xob = (np.trace(Sxp@partial_trace(rho8,2))).real # for e spin
        yob = (np.trace(Syp@partial_trace(rho8,2))).real 
        zob = (np.trace(Szp@partial_trace(rho8,2))).real

        xx = (np.trace(Ix@partial_trace(rho8,1))).real # for N spin
        yy = (np.trace(Iy@partial_trace(rho8,1))).real
        zz = (np.trace(Iz@partial_trace(rho8,1))).real
        
        cost = 1 - state_fidelity(irho_Z, partial_trace(rho8, 1))

        cost2 = 2 * vari[0] * vari[1] + vari[2] * vari[3]
        
        if cost < 0.01:
             if (cost2<trace[5] and vari[1] % 1 == 0 and vari[3] % 1 == 0):
                trace[0] = xx
                trace[1] = yy
                trace[2] = zz
                trace[4] = cost
                trace[5] = cost2
                vvv[0] = vari[0]
                vvv[1] = vari[1]
                vvv[2] = vari[2]
                vvv[3] = vari[3]
        if(cost < trace[6] and vari[1] % 1 == 0 and vari[3] % 1 == 0):
            trace[6] = cost
            normalxyz[0] = xx
            normalxyz[1] = yy
            normalxyz[2] = zz
            
            bbb[0] = vari[0]
            bbb[1] = vari[1]
            bbb[2] = vari[2]
            bbb[3] = vari[3]
        print("cost: " + str(cost) + "x: " + str(xx) + "y: " + str(yy) + "z: " + str(zz) + "N: " + str(vari[1]) + "tau: " + str(vari[0]) + "N2: " + str(vari[3]) + "tau2: " + str(vari[2]))
        return cost
        
aa = []
cc = []
dd = []
count = 1
tot_sum = 0
tolN = 1e-15

for ccc in tqdm(range(1)): # range 번의 실험을 진행한다.
    trace = [1, 1, 0, 100, 100, 1000, 100]
    vvv = [0, 0, 0, 0]
    bbb = [0, 0, 0, 0]
    normalxyz = [0, 0, 0]
    start = time.time()
    #for making 13C nuclear random dataset
    gammaN = 2*pi*1.071e-3 #[MHz/G]
    # Al    = 2*pi * random.uniform(0.05, 0.8) #[MHz] # A_|| hyperfine term
    # Ap = 2*pi* random.uniform(0.05, 0.3) #[MHz] # A_per hyperfine term
    Al = Alarr[number]
    Ap = Aparr[number]

    #Initialization
    rho_0 = (np.kron(U090xp,I))@irho@((np.kron(U090xp,I)).conj().T) # superposition state on NV

    Sa= []

    ham = Al*np.kron(sz,Iz) + Ap*np.kron(sz,Ix) + B*gammaN*np.kron(I,Iz) # Hamiltonian
    eigvals = np.linalg.eigh(ham)[0]            # diagonalizing the Hamiltonian 여기서부터 문제 
    eigvecs = -1*np.linalg.eigh(ham)[1]         # eigenvectors
    E = np.diag(eigvals)                        # exponent of eigenvalues
    U_H= eigvecs.conj().T                       # unitary matrix formed by eigenvectors
    

    for p in range(1): # 1번의 실험을 진행한다.(지역 최적화 알고리즘을 사용할 경우에 수정한다.)
        vari=[AA_predict[0][0], AA_predict[0][1], AA2_predict[0], AA2_predict[1]]  #초기값
        # bounds = [(0.85*tau,1.15*tau),(1.0,25.0),(0.00000000000000000001*tau,0.5*tau),(1.0,25.0)] #boundary
        if(AA_predict[0][1] < mean_absolute_error(y_input[:, 1], y_output[:, 1]) + 1):
            min_AA = 1
        else:
            min_AA = AA_predict[0][1] - mean_absolute_error(y_input[:, 1], y_output[:, 1])/2
        if(AA2_predict[1] < mean_absolute_error(y_input2[:, 1], y_output2[:, 1]) + 1):
            min_AA2 = 1   
        else:
            min_AA2 = AA2_predict - mean_absolute_error(y_input2[:, 1], y_output2[:, 1])/2
        bounds = [(float(AA_predict[0][0]) * float(1 - mean_absolute_error(y_input[:, 0], y_output[:, 0])), float(AA_predict[0][1]) * float(1 + mean_absolute_error(y_input[:, 0], y_output[:, 0]))), 
                  (min_AA, float(AA_predict[0][1] + mean_absolute_error(y_input[:, 1], y_output[:, 1]))), (float(AA2_predict[0]) * float(1 - mean_absolute_error(y_input2[:, 0], y_output2[:, 0])/2), float(AA2_predict[0]) * float(1 + mean_absolute_error(y_input2[:, 0], y_output2[:, 0])/2)), 
                  (min_AA2, float(AA2_predict[1] + mean_absolute_error(y_input2[:, 1], y_output2[:, 1])/2))]
        res4 = optimize.shgo(problem,bounds=bounds,iters=5,options={'xtol':1e-4,'ftol':1e-4}) #SHGO method
        # res4 = optimize.minimize(problem, AAdata, bounds=bounds ,method='Nelder-Mead',options={'xtol':tolN,'ftol':tolN}) #Nelder-Mead method
        res4['x'][1] = round(res4['x'][1]) #rounding
        res4['x'][3] = round(res4['x'][3]) #rounding
        dd.append([Al, Ap, trace[6], bbb[0], bbb[1], bbb[2], bbb[3], normalxyz[0], normalxyz[1], normalxyz[2], res4['nfev']])
        # cc.append([Al, Ap, trace[4], vvv[0], vvv[1], vvv[2], vvv[3], trace[0], trace[1], trace[2], res4["nfev"]])
        cc.append([Al, Ap, res4['fun'], res4['x'][0], res4['x'][1], res4['x'][2], res4['x'][3]])
        # aa.append([Al, Ap, trace[6], bbb[0], bbb[1], bbb[2], bbb[3], normalxyz[0], normalxyz[1], normalxyz[2], res4['nfev']])

        # if(np.abs(res4['fun']) < 0.1 and trace[0] != 1): #fidelity가 0.05보다 작으면 성공
        #     dd.append([Al, Ap, trace[6], bbb[0], bbb[1], bbb[2], bbb[3], normalxyz[0], normalxyz[1], normalxyz[2], res4['nfev']])
        #     cc.append([Al, Ap, trace[4], vvv[0], vvv[1], vvv[2], vvv[3], trace[0], trace[1], trace[2], res4["nfev"]])
        #     end = time.time()
        #     final = end - start
        #     count = count + 1
        # else:
        #     aa.append([Al, Ap, trace[6], bbb[0], bbb[1], bbb[2], bbb[3], normalxyz[0], normalxyz[1], normalxyz[2], res4['nfev']])
        #     end = time.time()
        #     final = end - start
        #     count = count + 1


# 결과들을 list에 저장하여 csv파일로 저장


print('success')

totalend = time.time()
print(totalend - totalstart)

print(dd)
print(cc)
aa = []
cc = []
dd = []
count = 1
tot_sum = 0
tolN = 1e-15

for ccc in tqdm(range(1)): # range 번의 실험을 진행한다.
    trace = [1, 1, 0, 100, 100, 1000, 100]
    vvv = [0, 0, 0, 0]
    bbb = [0, 0, 0, 0]
    normalxyz = [0, 0, 0]
    start = time.time()
    #for making 13C nuclear random dataset
    gammaN = 2*pi*1.071e-3 #[MHz/G]
    # Al    = 2*pi * random.uniform(0.05, 0.8) #[MHz] # A_|| hyperfine term
    # Ap = 2*pi* random.uniform(0.05, 0.3) #[MHz] # A_per hyperfine term
    Al = Alarr[number]
    Ap = Aparr[number]

    #Initialization
    rho_0 = (np.kron(U090xp,I))@irho@((np.kron(U090xp,I)).conj().T) # superposition state on NV

    Sa= []

    ham = Al*np.kron(sz,Iz) + Ap*np.kron(sz,Ix) + B*gammaN*np.kron(I,Iz) # Hamiltonian
    eigvals = np.linalg.eigh(ham)[0]            # diagonalizing the Hamiltonian 여기서부터 문제 
    eigvecs = -1*np.linalg.eigh(ham)[1]         # eigenvectors
    E = np.diag(eigvals)                        # exponent of eigenvalues
    U_H= eigvecs.conj().T                       # unitary matrix formed by eigenvectors
    

    for p in range(1): # 1번의 실험을 진행한다.(지역 최적화 알고리즘을 사용할 경우에 수정한다.)
        vari=[AA_predict[0][0], AA_predict[0][1], AA2_predict[0], AA2_predict[1]]  #초기값
        # bounds = [(0.85*tau,1.15*tau),(1.0,25.0),(0.00000000000000000001*tau,0.5*tau),(1.0,25.0)] #boundary
        if(AA_predict[0][1] < mean_absolute_error(y_input[:, 1], y_output[:, 1]) + 1):
            min_AA = 1
        else:
            min_AA = AA_predict[0][1] - mean_absolute_error(y_input[:, 1], y_output[:, 1])/2
        if(AA2_predict[1] < mean_absolute_error(y_input2[:, 1], y_output2[:, 1]) + 1):
            min_AA2 = 1   
        else:
            min_AA2 = AA2_predict - mean_absolute_error(y_input2[:, 1], y_output2[:, 1])/2
        bounds = [(float(AA_predict[0][0]) * float(1 - mean_absolute_error(y_input[:, 0], y_output[:, 0])), float(AA_predict[0][1]) * float(1 + mean_absolute_error(y_input[:, 0], y_output[:, 0]))), 
                  (min_AA, float(AA_predict[0][1] + mean_absolute_error(y_input[:, 1], y_output[:, 1]))), (float(AA2_predict[0]) * float(1 - mean_absolute_error(y_input2[:, 0], y_output2[:, 0])/2), float(AA2_predict[0]) * float(1 + mean_absolute_error(y_input2[:, 0], y_output2[:, 0])/2)), 
                  (min_AA2, float(AA2_predict[1] + mean_absolute_error(y_input2[:, 1], y_output2[:, 1])/2))]
        # res4 = optimize.shgo(problem,bounds=bounds,iters=5,options={'xtol':1e-4,'ftol':1e-4}) #SHGO method
        res4 = optimize.minimize(problem, AAdata, bounds=bounds ,method='Nelder-Mead',options={'xtol':tolN,'ftol':tolN}) #Nelder-Mead method
        res4['x'][1] = round(res4['x'][1]) #rounding
        res4['x'][3] = round(res4['x'][3]) #rounding
        dd.append([Al, Ap, trace[6], bbb[0], bbb[1], bbb[2], bbb[3], normalxyz[0], normalxyz[1], normalxyz[2], res4['nfev']])
        # cc.append([Al, Ap, trace[4], vvv[0], vvv[1], vvv[2], vvv[3], trace[0], trace[1], trace[2], res4["nfev"]])
        cc.append([Al, Ap, res4['fun'], res4['x'][0], res4['x'][1], res4['x'][2], res4['x'][3]])


print('success')

totalend = time.time()
print(totalend - totalstart)

print(dd)
print(cc)

2023-04-25 10:52:04.461000

  0%|          | 0/1 [00:00<?, ?it/s]

cost: 0.5004857925161492x: 4.410823744596779e-05y: -9.024964984952026e-07z: 0.0009715850322954966N: 12.24276839188167tau: 2.100846761477364N2: 1.0tau2: 0.5141143178250699
cost: 0.5002024117303427x: -2.2378798273460336e-05y: 0.00010573890777611792z: 0.00040482346068748676N: 14.527183324268886tau: 16.530859754506544N2: 3.192072629928589tau2: 0.7112161541674229
cost: 0.4996095359077868x: -2.2013353795189957e-05y: 2.2375078992076377e-05z: -0.0007809281844244342N: 12.24276839188167tau: 16.530859754506544N2: 1.0tau2: 0.5141143178250699
cost: 0.5004757980599945x: 6.069299057927507e-05y: 3.5315754900546326e-05z: 0.0009515961199914047N: 14.527183324268886tau: 16.530859754506544N2: 1.0tau2: 0.5141143178250699
cost: 0.5001785902088502x: 9.582431161042583e-05y: -1.6124369927260872e-05z: 0.00035718041770316233N: 14.527183324268886tau: 16.530859754506544N2: 1.0tau2: 0.7112161541674229
cost: 0.5007417910562135x: 7.961695146451928e-05y: 2.325356000307862e-05z: 0.0014835821124282722N: 14.527183324268886tau: 16.530859754506544N2: 3.192072629928589tau2: 0.5141143178250699
cost: 0.49965698944632475x: 4.889790245598711e-05y: 4.275133267628902e-06z: -0.0006860211073485001N: 12.24276839188167tau: 16.530859754506544N2: 1.0tau2: 0.7112161541674229
cost: 0.4998812189607401x: 3.6806830474657914e-05y: 6.7367593875255e-05z: -0.00023756207851738376N: 12.24276839188167tau: 16.530859754506544N2: 3.192072629928589tau2: 0.7112161541674229
cost: 0.4999736363605507x: -3.239756546243337e-06y: 1.0831253521798815e-05z: -5.272727889704676e-05N: 12.24276839188167tau: 16.530859754506544N2: 3.192072629928589tau2: 0.5141143178250699
cost: 0.4995360863994117x: -4.296529223672858e-05y: -7.098866849196243e-06z: -0.0009278272011795652N: 14.527183324268886tau: 2.100846761477364N2: 1.0tau2: 0.5141143178250699
cost: 0.49959009754037753x: 4.902773218950032e-05y: -8.14545192729982e-06z: -0.0008198049192484902N: 14.527183324268886tau: 2.100846761477364N2: 1.0tau2: 0.7112161541674229
cost: 0.49985850875068105x: 4.604654803961618e-05y: 5.30030366001316e-05z: -0.0002829824986421148N: 14.527183324268886tau: 2.100846761477364N2: 3.192072629928589tau2: 0.7112161541674229
cost: 0.4999663173616782x: -3.059882292005215e-06y: -4.048134587183235e-06z: -6.736527664802372e-05N: 14.527183324268886tau: 2.100846761477364N2: 3.192072629928589tau2: 0.5141143178250699
cost: 0.5000595064241815x: -1.8931182630859355e-05y: 2.720235500531024e-05z: 0.00011901284836063342N: 12.24276839188167tau: 2.100846761477364N2: 1.0tau2: 0.7112161541674229
cost: 0.5002945202121005x: -4.740314118469209e-05y: -5.471362555809216e-06z: 0.0005890404241976066N: 12.24276839188167tau: 2.100846761477364N2: 3.192072629928589tau2: 0.7112161541674229
cost: 0.5002276377855763x: 2.006065572568704e-05y: 1.253454555620679e-06z: 0.0004552755711488832N: 12.24276839188167tau: 2.100846761477364N2: 3.192072629928589tau2: 0.5141143178250699
cost: 0.5000054197935173x: 4.347985155572624e-05y: -3.906032005688968e-05z: 1.083958702979837e-05N: 13.38497585807528tau: 9.315853257991954N2: 2.0960363149642944tau2: 0.6126652359962463
cost: 0.49971791190406956x: 5.782606673358261e-05y: -1.658400314638337e-05z: -0.0005641761918643295N: 13.38497585807528tau: 2.100846761477364N2: 2.0960363149642944tau2: 0.6126652359962463
cost: 0.5001761893555443x: 6.924110241887091e-05y: 2.1705782705731076e-05z: 0.00035237871108617647N: 12.24276839188167tau: 2.100846761477364N2: 2.0960363149642944tau2: 0.6126652359962463
cost: 0.5001062652404589x: 1.0055562412801685e-05y: -3.199820402723791e-06z: 0.00021253048091496307N: 12.24276839188167tau: 2.100846761477364N2: 2.0960363149642944tau2: 0.5141143178250699
cost: 0.5000856604387921x: 2.7307000422133643e-05y: 1.5455445515914898e-05z: 0.00017132087758114922N: 12.24276839188167tau: 2.100846761477364N2: 1.0tau2: 0.6126652359962463
cost: 0.5002836860549918x: 1.7846944633324e-05y: 1.2162504632714437e-06z: 0.0005673721099796469N: 13.38497585807528tau: 2.100846761477364N2: 2.0960363149642944tau2: 0.5141143178250699
cost: 0.49987582371720474x: -8.668910278622315e-06y: -1.0481010294617274e-06z: -0.0002483525655939678N: 13.38497585807528tau: 2.100846761477364N2: 1.0tau2: 0.5141143178250699
cost: 0.49992549625082816x: 4.0863060289185894e-05y: -9.343831299554566e-06z: -0.00014900749834628746N: 13.38497585807528tau: 2.100846761477364N2: 1.0tau2: 0.6126652359962463
cost: 0.4999823971302626x: -9.429279228752026e-06y: -1.1089557056497598e-05z: -3.520573947934924e-05N: 12.24276839188167tau: 9.315853257991954N2: 2.0960363149642944tau2: 0.6126652359962463
cost: 0.4999351487480549x: -6.3855051414763984e-06y: 8.378662131264605e-07z: -0.0001297025038949906N: 12.24276839188167tau: 9.315853257991954N2: 2.0960363149642944tau2: 0.5141143178250699
cost: 0.4998867639076886x: -1.1242059612159107e-05y: -1.3772965745872056e-06z: -0.0002264721846272355N: 12.24276839188167tau: 9.315853257991954N2: 1.0tau2: 0.5141143178250699
cost: 0.49999707110059965x: -1.5837047501724875e-06y: -5.913798395340585e-06z: -5.857798804909109e-06N: 12.24276839188167tau: 9.315853257991954N2: 1.0tau2: 0.6126652359962463
cost: 0.499386949244518x: -5.1816018725217225e-05y: -8.736903805872068e-06z: -0.0012261015109693574N: 13.38497585807528tau: 9.315853257991954N2: 2.0960363149642944tau2: 0.5141143178250699
cost: 0.4996890077716021x: -2.416338424928604e-05y: -1.676326829922782e-05z: -0.0006219844568007837N: 13.38497585807528tau: 9.315853257991954N2: 1.0tau2: 0.5141143178250699
cost: 0.499954452664923x: 3.016306916639672e-05y: -9.071075808430099e-06z: -9.109467015899764e-05N: 13.38497585807528tau: 9.315853257991954N2: 1.0tau2: 0.6126652359962463
cost: 0.4944215311776655x: 0.00021181051022148983y: -5.238983387886604e-07z: -0.011156937644671683N: 12.813872124978474tau: 5.708350009734659N2: 1.5480181574821472tau2: 0.5633897769106582
cost: 0.5003350038878838x: 0.00011199903370811919y: -1.3485531774719024e-06z: 0.0006700077757693101N: 13.38497585807528tau: 16.530859754506544N2: 2.0960363149642944tau2: 0.6126652359962463
cost: 0.500557403436662x: 0.00010035767905668916y: -8.311151163917056e-05z: 0.0011148068733262129N: 14.527183324268886tau: 16.530859754506544N2: 2.0960363149642944tau2: 0.6126652359962463
cost: 0.4999441615885146x: 3.3817799178444564e-05y: 6.658655945958152e-05z: -0.00011167682296819859N: 14.527183324268886tau: 16.530859754506544N2: 2.0960363149642944tau2: 0.7112161541674229
cost: 0.5004720154427189x: 8.726520904518567e-05y: -0.00011688408694510415z: 0.0009440308854408719N: 14.527183324268886tau: 16.530859754506544N2: 3.192072629928589tau2: 0.6126652359962463
cost: 0.5003017425075434x: -7.470249402792692e-05y: 7.876464614497264e-05z: 0.0006034850150892224N: 13.38497585807528tau: 16.530859754506544N2: 2.0960363149642944tau2: 0.7112161541674229
cost: 0.5004389567836889x: -7.505233388620074e-05y: 3.068338660646341e-05z: 0.0008779135673802618N: 13.38497585807528tau: 16.530859754506544N2: 3.192072629928589tau2: 0.7112161541674229
cost: 0.5004456965768675x: 0.00016434891207391241y: -2.065656955773103e-05z: 0.0008913931537370412N: 13.38497585807528tau: 16.530859754506544N2: 3.192072629928589tau2: 0.6126652359962463
cost: 0.4999415003639217x: 4.0309840009924124e-05y: 3.9368534623514424e-05z: -0.00011699927216202166N: 14.527183324268886tau: 9.315853257991954N2: 2.0960363149642944tau2: 0.6126652359962463
cost: 0.49989722847276175x: -2.3259725088517307e-05y: 5.8298867785714845e-05z: -0.00020554305448172716N: 14.527183324268886tau: 9.315853257991954N2: 2.0960363149642944tau2: 0.7112161541674229
cost: 0.500000117173878x: -3.844998568304145e-05y: 3.666214333460094e-06z: 2.3434775087149973e-07N: 14.527183324268886tau: 9.315853257991954N2: 3.192072629928589tau2: 0.7112161541674229
cost: 0.5000138053085279x: 6.442141533252472e-05y: 2.2757909426282964e-05z: 2.761061704981138e-05N: 14.527183324268886tau: 9.315853257991954N2: 3.192072629928589tau2: 0.6126652359962463
cost: 0.49963907428972854x: 4.229636087363157e-05y: 8.044665382255867e-05z: -0.0007218514205480364N: 13.38497585807528tau: 9.315853257991954N2: 2.0960363149642944tau2: 0.7112161541674229
cost: 0.49994238318520956x: -2.003087947357717e-06y: 5.67268623691121e-05z: -0.00011523362958576477N: 13.38497585807528tau: 9.315853257991954N2: 3.192072629928589tau2: 0.7112161541674229
cost: 0.49998417516784255x: 2.6346496623131082e-05y: -8.180627627412339e-05z: -3.1649664320620996e-05N: 13.38497585807528tau: 9.315853257991954N2: 3.192072629928589tau2: 0.6126652359962463
cost: 0.49971838768721044x: 8.090173625394808e-05y: -6.468670263141225e-05z: -0.0005632246255816709N: 13.956079591172083tau: 12.923356506249249N2: 2.6440544724464417tau2: 0.6619406950818346
cost: 0.49999124645443294x: 1.1019358794935735e-06y: -4.1860519022391264e-05z: -1.7507091131907515e-05N: 12.24276839188167tau: 16.530859754506544N2: 2.0960363149642944tau2: 0.6126652359962463
cost: 0.4995347028883321x: -3.002925813594187e-05y: 2.523623255629116e-06z: -0.0009305942233341913N: 12.24276839188167tau: 16.530859754506544N2: 2.0960363149642944tau2: 0.5141143178250699
cost: 0.49999347869795774x: 1.0746781071124941e-05y: -1.8075649351103587e-05z: -1.30426040820808e-05N: 12.24276839188167tau: 16.530859754506544N2: 1.0tau2: 0.6126652359962463
cost: 0.5000700151984576x: 5.737426011622913e-06y: 1.5210102937791088e-05z: 0.00014003039691706798N: 13.38497585807528tau: 16.530859754506544N2: 2.0960363149642944tau2: 0.5141143178250699
cost: 0.5006847257389806x: 4.12458739184557e-05y: 1.749682006673748e-05z: 0.0013694514779636346N: 13.38497585807528tau: 16.530859754506544N2: 1.0tau2: 0.5141143178250699
cost: 0.5002022816612968x: 5.522509550807877e-05y: 6.223908716833414e-06z: 0.00040456332259586336N: 13.38497585807528tau: 16.530859754506544N2: 1.0tau2: 0.6126652359962463
cost: 0.494992368323374x: 0.0006618343957071251y: 2.1762338839831016e-05z: -0.010015263353254034N: 12.813872124978474tau: 12.923356506249249N2: 1.5480181574821472tau2: 0.5633897769106582
cost: 0.5000365099437637x: 1.9041496821883136e-05y: -7.303228782796697e-06z: 7.301988752900224e-05N: 14.527183324268886tau: 16.530859754506544N2: 2.0960363149642944tau2: 0.5141143178250699
cost: 0.5005684353306289x: 8.922294023504728e-05y: -4.026314361897437e-05z: 0.0011368706612604473N: 14.527183324268886tau: 16.530859754506544N2: 1.0tau2: 0.6126652359962463
cost: 0.4993742831048329x: -3.9249364204634214e-05y: -1.3299220592238523e-05z: -0.0012514337903399286N: 14.527183324268886tau: 9.315853257991954N2: 2.0960363149642944tau2: 0.5141143178250699
cost: 0.49996488768528013x: 5.945984274470127e-06y: -5.043816562278012e-06z: -7.022462944494823e-05N: 14.527183324268886tau: 9.315853257991954N2: 1.0tau2: 0.5141143178250699
cost: 0.499827679721524x: 9.684618446940615e-06y: 3.1025745592485276e-05z: -0.00034464055695715423N: 14.527183324268886tau: 9.315853257991954N2: 1.0tau2: 0.6126652359962463
cost: 0.49985615085704194x: -5.3941507075315064e-05y: -3.68350552074799e-05z: -0.0002876982859186805N: 13.956079591172083tau: 12.923356506249249N2: 1.5480181574821472tau2: 0.5633897769106582
cost: 0.5000238147632694x: -8.581378119966454e-06y: 5.47635336280037e-05z: 4.762952654102648e-05N: 13.38497585807528tau: 16.530859754506544N2: 1.0tau2: 0.7112161541674229
cost: 0.49966506762964547x: -8.139229148350466e-06y: 5.543108712456396e-05z: -0.0006698647407142322N: 14.527183324268886tau: 9.315853257991954N2: 1.0tau2: 0.7112161541674229
cost: 0.4995630122261072x: 3.605687619474265e-05y: 3.6073852869460946e-05z: -0.0008739755477903399N: 13.38497585807528tau: 9.315853257991954N2: 1.0tau2: 0.7112161541674229
cost: 0.49985463971197086x: 2.6861598168133934e-05y: -3.617432423374178e-05z: -0.00029072057606083224N: 13.956079591172083tau: 12.923356506249249N2: 1.5480181574821472tau2: 0.6619406950818346
cost: 0.500419045074164x: 2.8851848973912098e-05y: 1.2476673391032585e-06z: 0.0008380901483297509N: 13.38497585807528tau: 16.530859754506544N2: 3.192072629928589tau2: 0.5141143178250699
cost: 0.5000255619903597x: 5.539549349347847e-06y: 4.5042728936770665e-06z: 5.112398071338564e-05N: 14.527183324268886tau: 9.315853257991954N2: 3.192072629928589tau2: 0.5141143178250699
cost: 0.5000099519744476x: 5.107954365771595e-06y: -4.379305469582456e-06z: 1.9903948888955192e-05N: 13.38497585807528tau: 9.315853257991954N2: 3.192072629928589tau2: 0.5141143178250699
cost: 0.4993448813412489x: -0.0001491763149306885y: -1.0564686540874297e-05z: -0.0013102373175046256N: 13.956079591172083tau: 12.923356506249249N2: 2.6440544724464417tau2: 0.5633897769106582
cost: 0.4996166368464767x: 8.364419296327829e-05y: 5.697131121355282e-05z: -0.0007667263070448849N: 12.24276839188167tau: 16.530859754506544N2: 2.0960363149642944tau2: 0.7112161541674229
cost: 0.4999115447427407x: 1.6078587694996174e-05y: 1.4974912714635691e-06z: -0.00017691051452334294N: 12.24276839188167tau: 9.315853257991954N2: 2.0960363149642944tau2: 0.7112161541674229
cost: 0.4999536641255026x: 7.899090601280086e-06y: -4.043180980930941e-06z: -9.267174899973973e-05N: 12.24276839188167tau: 9.315853257991954N2: 1.0tau2: 0.7112161541674229
cost: 0.5069676742342534x: 0.000999510652897228y: 7.586945376936594e-05z: 0.013935348468504416N: 12.813872124978474tau: 12.923356506249249N2: 1.5480181574821472tau2: 0.6619406950818346
cost: 0.49992671710282577x: -3.3923083174472674e-05y: -6.48816490123748e-05z: -0.00014656579434635386N: 12.24276839188167tau: 16.530859754506544N2: 3.192072629928589tau2: 0.6126652359962463
cost: 0.49994541340436416x: 1.0409069029066718e-05y: 7.0832795212897e-06z: -0.00010917319127634606N: 12.24276839188167tau: 9.315853257991954N2: 3.192072629928589tau2: 0.7112161541674229
cost: 0.4999592310157924x: -2.144930501011324e-05y: -1.4118713344515757e-05z: -8.15379684198092e-05N: 12.24276839188167tau: 9.315853257991954N2: 3.192072629928589tau2: 0.6126652359962463
cost: 0.5080321038972508x: 0.0016228370455266122y: 0.00013402074550468565z: 0.01606420779449924N: 12.813872124978474tau: 12.923356506249249N2: 2.6440544724464417tau2: 0.6619406950818346
cost: 0.4999728599643758x: -2.6975335643444724e-06y: -1.208626211807065e-06z: -5.428007125385381e-05N: 12.24276839188167tau: 9.315853257991954N2: 3.192072629928589tau2: 0.5141143178250699
cost: 0.4959323649944165x: 0.00021903443626714904y: -1.183994153409855e-05z: -0.008135270011169482N: 12.813872124978474tau: 12.923356506249249N2: 2.6440544724464417tau2: 0.5633897769106582
cost: 0.4999955529164146x: -8.246912864639296e-06y: -6.18865175089318e-05z: -8.89416717470004e-06N: 14.527183324268886tau: 2.100846761477364N2: 2.0960363149642944tau2: 0.6126652359962463
cost: 0.49945720459845466x: -4.748514209440254e-05y: 3.205296602432333e-07z: -0.0010855908030943384N: 14.527183324268886tau: 2.100846761477364N2: 2.0960363149642944tau2: 0.5141143178250699
cost: 0.49999620269257694x: 1.1552245616390684e-05y: -2.9109998840778787e-05z: -7.594614849171233e-06N: 14.527183324268886tau: 2.100846761477364N2: 1.0tau2: 0.6126652359962463
cost: 0.49664550935142837x: 0.00016542650569474453y: -4.5190991825620405e-05z: -0.006708981297146033N: 13.956079591172083tau: 5.708350009734659N2: 1.5480181574821472tau2: 0.5633897769106582
cost: 0.4995394336307486x: 8.936871789839767e-05y: 3.3314503634220265e-05z: -0.0009211327385066359N: 14.527183324268886tau: 2.100846761477364N2: 2.0960363149642944tau2: 0.7112161541674229
cost: 0.5001070426140166x: 3.4715708029853546e-05y: -6.480685895392246e-07z: 0.00021408522803001429N: 13.38497585807528tau: 2.100846761477364N2: 2.0960363149642944tau2: 0.7112161541674229
cost: 0.5006939077557484x: 0.00013736527296395566y: -7.171624992686229e-06z: 0.001387815511493251N: 13.38497585807528tau: 2.100846761477364N2: 1.0tau2: 0.7112161541674229
cost: 0.4962739590789639x: 0.0005213614068415584y: -7.29986859700632e-05z: -0.00745208184207502N: 13.956079591172083tau: 5.708350009734659N2: 1.5480181574821472tau2: 0.6619406950818346
cost: 0.49992150576746175x: -5.953519179196197e-05y: -8.940955361384762e-05z: -0.00015698846508033215N: 14.527183324268886tau: 2.100846761477364N2: 3.192072629928589tau2: 0.6126652359962463
cost: 0.49941896124877927x: -0.00011904058104510347y: 8.339813540957043e-06z: -0.0011620775024447916N: 13.38497585807528tau: 2.100846761477364N2: 3.192072629928589tau2: 0.7112161541674229
cost: 0.49960295878958094x: 5.846078404795653e-05y: -1.9750130862497724e-05z: -0.0007940824208415576N: 13.38497585807528tau: 2.100846761477364N2: 3.192072629928589tau2: 0.6126652359962463
cost: 0.49835023617319296x: 0.0011959320202223882y: -0.00012275596297659473z: -0.0032995276536169627N: 13.956079591172083tau: 5.708350009734659N2: 2.6440544724464417tau2: 0.6619406950818346
cost: 0.4999466827150102x: -2.2792690753279873e-06y: -1.2354643108298397e-06z: -0.00010663456998383225N: 13.38497585807528tau: 2.100846761477364N2: 3.192072629928589tau2: 0.5141143178250699
cost: 0.5026847001700805x: -3.522459193118152e-05y: -6.68192070136641e-05z: 0.005369400340158315N: 13.956079591172083tau: 5.708350009734659N2: 2.6440544724464417tau2: 0.5633897769106582
cost: 0.5002738016185505x: -5.716926425657174e-05y: 2.292255401700413e-05z: 0.0005476032370977935N: 12.24276839188167tau: 2.100846761477364N2: 2.0960363149642944tau2: 0.7112161541674229
cost: 0.5018062175932319x: 0.0008054806936460086y: -8.864448087871415e-06z: 0.0036124351864610382N: 12.813872124978474tau: 5.708350009734659N2: 1.5480181574821472tau2: 0.6619406950818346
cost: 0.5002675116391625x: 0.0001158711056899476y: 1.705000655300012e-05z: 0.0005350232783216113N: 12.24276839188167tau: 2.100846761477364N2: 3.192072629928589tau2: 0.6126652359962463
cost: 0.5040085625562527x: 0.0014734114762864573y: -1.5659836176629138e-05z: 0.008017125112502632N: 12.813872124978474tau: 5.708350009734659N2: 2.6440544724464417tau2: 0.6619406950818346
cost: 0.4996368925585408x: 3.642390968505954e-05y: -1.0731343458407483e-06z: -0.0007262148829212944N: 12.813872124978474tau: 5.708350009734659N2: 2.6440544724464417tau2: 0.5633897769106582
cost: 0.4999546902694465x: -7.5821766814267145e-06y: -3.7789908661354154e-06z: -9.061946111149632e-05N: 12.813872124978474tau: 9.315853257991954N2: 1.5480181574821472tau2: 0.5633897769106582
cost: 0.49997674540516923x: 7.044162903322663e-06y: -2.0545164845330055e-05z: -4.6509189666643636e-05N: 13.38497585807528tau: 9.315853257991954N2: 1.5480181574821472tau2: 0.5633897769106582
cost: 0.499954452664923x: 3.016306916639672e-05y: -9.071075808430099e-06z: -9.109467015899764e-05N: 13.38497585807528tau: 9.315853257991954N2: 1.5480181574821472tau2: 0.6126652359962463
cost: 0.4995816829181111x: -5.105156980847003e-05y: -4.815257033082693e-05z: -0.0008366341637828789N: 13.38497585807528tau: 9.315853257991954N2: 2.0960363149642944tau2: 0.5633897769106582
cost: 0.49999707110059965x: -1.5837047501724875e-06y: -5.913798395340585e-06z: -5.857798804909109e-06N: 12.813872124978474tau: 9.315853257991954N2: 1.5480181574821472tau2: 0.6126652359962463
cost: 0.4999823971302626x: -9.429279228752026e-06y: -1.1089557056497598e-05z: -3.520573947934924e-05N: 12.813872124978474tau: 9.315853257991954N2: 2.0960363149642944tau2: 0.6126652359962463
cost: 0.4998837643847689x: -1.925971005777374e-05y: -2.2980275447578944e-06z: -0.00023247123046682416N: 12.813872124978474tau: 9.315853257991954N2: 2.0960363149642944tau2: 0.5633897769106582
cost: 0.49664550935142837x: 0.00016542650569474453y: -4.5190991825620405e-05z: -0.006708981297146033N: 13.38497585807528tau: 5.708350009734659N2: 1.5480181574821472tau2: 0.5633897769106582
cost: 0.49430371232318926x: 0.00032122092388854086y: -5.738393501200211e-05z: -0.011392575353623868N: 13.38497585807528tau: 5.708350009734659N2: 1.5480181574821472tau2: 0.6126652359962463
cost: 0.4950815399953554x: 0.0006490586388891023y: -0.00011499337615600465z: -0.009836920009291927N: 13.38497585807528tau: 5.708350009734659N2: 2.0960363149642944tau2: 0.6126652359962463
cost: 0.5026847001700805x: -3.522459193118152e-05y: -6.68192070136641e-05z: 0.005369400340158315N: 13.38497585807528tau: 5.708350009734659N2: 2.0960363149642944tau2: 0.5633897769106582

  0%|          | 0/1 [02:12<?, ?it/s]

cost: 0.008776957879768066x: 0.01055842098963886y: -0.08512060406886227z: -0.9824460842404668N: 13.242199924801078tau: 15.65130786182944N2: 2.7810590118169785tau2: 0.6619406950818346
cost: 0.008777129458672484x: 0.010558697226883539y: -0.08512072884140684z: -0.9824457410826546N: 13.242199924801078tau: 15.651307876730602N2: 2.7810590118169785tau2: 0.6619406950818346
cost: 0.008776957879768066x: 0.01055842098963886y: -0.08512060406886227z: -0.9824460842404668N: 13.242199939702239tau: 15.65130786182944N2: 2.7810590118169785tau2: 0.6619406950818346
cost: 0.008776980369614162x: 0.010558428080348623y: -0.08512062392577918z: -0.9824460392607746N: 13.242199924801078tau: 15.65130786182944N2: 2.7810590118169785tau2: 0.6619407099829958
cost: 0.008776957879768066x: 0.01055842098963886y: -0.08512060406886227z: -0.9824460842404668N: 13.242199924801078tau: 15.65130786182944N2: 2.7810590267181396tau2: 0.6619406950818346
cost: 0.007514020783374931x: 0.00675763006516859y: -0.08322464924331294z: -0.9849719584332546N: 13.242199924801078tau: 15.65109760196352N2: 2.7810590118169785tau2: 0.6619406950818346
cost: 0.00751402790847433x: 0.006757892293767409y: -0.08322479310133869z: -0.9849719441830589N: 13.242199924801078tau: 15.651097616864682N2: 2.7810590118169785tau2: 0.6619406950818346
cost: 0.007514020783374931x: 0.00675763006516859y: -0.08322464924331294z: -0.9849719584332546N: 13.242199939702239tau: 15.65109760196352N2: 2.7810590118169785tau2: 0.6619406950818346
cost: 0.007514023478184639x: 0.006757636066429495y: -0.0832246702498462z: -0.9849719530436357N: 13.242199924801078tau: 15.65109760196352N2: 2.7810590118169785tau2: 0.6619407099829958
cost: 0.007514020783374931x: 0.00675763006516859y: -0.08322464924331294z: -0.9849719584332546N: 13.242199924801078tau: 15.65109760196352N2: 2.7810590267181396tau2: 0.6619406950818346
cost: 0.49489803935713894x: 0.00022595935317731158y: -0.00020787701747165648z: -0.010203921285721285N: 13.527751791349479tau: 3.002722573541688N2: 1.685022696852684tau2: 0.6249841007676434
cost: 0.4948980094798541x: 0.00022596021660151004y: -0.0002078772028574049z: -0.0102039810402893N: 13.527751791349479tau: 3.002722588442849N2: 1.685022696852684tau2: 0.6249841007676434
cost: 0.49489803935713894x: 0.00022595935317731158y: -0.00020787701747165648z: -0.010203921285721285N: 13.52775180625064tau: 3.002722573541688N2: 1.685022696852684tau2: 0.6249841007676434
cost: 0.4948980384140209x: 0.00022595939348687196y: -0.00020787703795150693z: -0.010203923171956952N: 13.527751791349479tau: 3.002722573541688N2: 1.685022696852684tau2: 0.6249841156688046
cost: 0.49489803935713894x: 0.00022595935317731158y: -0.00020787701747165648z: -0.010203921285721285N: 13.527751791349479tau: 3.002722573541688N2: 1.6850227117538452tau2: 0.6249841007676434
cost: 0.500079143746647x: 3.486910521066774e-05y: 4.370741982095321e-05z: 0.00015828749329072078N: 13.527751791349479tau: 3.9045983856060116N2: 1.685022696852684tau2: 0.6373029655390405
cost: 0.5005124338338133x: 0.0005612628828375456y: 1.2294838570466038e-06z: 0.0010248676676277158N: 13.527751791349479tau: 3.4523726983412018N2: 1.685022696852684tau2: 0.631125943145219
cost: 0.4963564841876881x: 0.0008999574553075155y: -2.3004594036873157e-05z: -0.007287031624624518N: 13.527751791349479tau: 3.2261568198241943N2: 1.685022696852684tau2: 0.6280360245784762
cost: 0.5036657699194924x: 0.0006332419526895016y: 7.188632798668139e-05z: 0.007331539838982937N: 13.527751791349479tau: 3.11407733619724N2: 1.685022696852684tau2: 0.6265051131337085
cost: 0.4942359235493896x: 0.00040024789676136076y: -5.434012067480343e-05z: -0.01152815290121978N: 13.527751791349479tau: 3.0562970104989478N2: 1.685022696852684tau2: 0.6257158824999527
cost: 0.4927422835204174x: 0.00031200111268622766y: -0.00013850066747366982z: -0.014515432959165575N: 13.527751791349479tau: 3.029675857666899N2: 1.685022696852684tau2: 0.6253522599508058
cost: 0.5044003216670152x: 0.0006164754809922486y: 0.0001725326592944658z: 0.008800643334028024N: 13.527751791349479tau: 3.0167588864613846N2: 1.685022696852684tau2: 0.6251758249922359
cost: 0.4934057341591007x: 0.000814300002245489y: -7.854782774785636e-05z: -0.013188531681799343N: 13.527751791349479tau: 3.0079698150304224N2: 1.685022696852684tau2: 0.6250557736714489
cost: 0.4934057688471647x: 0.0008143024438553737y: -7.854702270833173e-05z: -0.013188462305669613N: 13.527751791349479tau: 3.0079698299315836N2: 1.685022696852684tau2: 0.6250557736714489
cost: 0.4934057341591007x: 0.000814300002245489y: -7.854782774785636e-05z: -0.013188531681799343N: 13.52775180625064tau: 3.0079698150304224N2: 1.685022696852684tau2: 0.6250557736714489

KeyboardInterrupt: